# 進階的 SQL 五十道練習

> 進階的 SQL 查詢

[數聚點](https://www.datainpoint.com) | 郭耀仁 <yaojenkuo@datainpoint.com>

## 練習題指引

- 仔細閱讀題目敘述並且在自己的電腦透過 DBeaver 完成。
- 下載批改測試檔案並放置在自己熟悉的目錄（資料夾）之中。
    - 批改測試檔案：[ch09-test-advanced-query.py](https://classroom-hahow-sqlfiftyplus.s3.ap-northeast-1.amazonaws.com/test_scripts/ch09-test-advanced-query.py)
- 執行測試：
    - 開啟 Anaconda Prompt（Windows 作業系統）或 Terminal（macOS）
    - 啟動專案環境 `conda activate pythonmysql`
    - 透過 `cd` 指令移動到放置批改測試檔案的目錄（資料夾）。
    - 執行 `python ch09-test-advanced-query.py root {roots_password}`
- 終端機操作的技巧：
    - 在終端機畫面中按「向上箭頭」可以叫出先前執行過的指令。
    - Windows 作業系統可以使用 `cls` 指令清空 Anaconda Prompt 畫面；macOS 可以使用 `clear` 指令或 `Ctrl - L` 清空 Terminal 畫面。

## 0901 在本機 MySQL Server 的 `covid19` 資料庫，建立一個檢視表 `date_difference` 顯示 `accumulative_cases` 資料表與 `calendars` 資料表兩者的日期資料差集，亦即哪些日期在 `calendars` 資料表之中，卻沒有出現在 `accumulative_cases` 資料表中。

```sql
SELECT *
  FROM covid19.date_difference;
```

|id|recorded_on|
|--|-----------|
|1|2020-01-01|
|2|2020-01-02|
|3|2020-01-03|
|4|2020-01-04|
|5|2020-01-05|
|6|2020-01-06|
|7|2020-01-07|
|8|2020-01-08|
|9|2020-01-09|
|10|2020-01-10|
|11|2020-01-11|
|12|2020-01-12|
|13|2020-01-13|
|14|2020-01-14|
|15|2020-01-15|
|16|2020-01-16|
|17|2020-01-17|
|18|2020-01-18|
|19|2020-01-19|
|20|2020-01-20|
|21|2020-01-21|
|1165|2023-03-10|
|1166|2023-03-11|
|1167|2023-03-12|
|1168|2023-03-13|
|1169|2023-03-14|
|1170|2023-03-15|
|1171|2023-03-16|
|1172|2023-03-17|
|1173|2023-03-18|
|1174|2023-03-19|
|1175|2023-03-20|
|1176|2023-03-21|
|1177|2023-03-22|
|1178|2023-03-23|
|1179|2023-03-24|
|1180|2023-03-25|
|1181|2023-03-26|
|1182|2023-03-27|
|1183|2023-03-28|
|1184|2023-03-29|
|1185|2023-03-30|
|1186|2023-03-31|
|1187|2023-04-01|
|1188|2023-04-02|
|1189|2023-04-03|
|1190|2023-04-04|
|1191|2023-04-05|
|1192|2023-04-06|
|1193|2023-04-07|
|1194|2023-04-08|
|1195|2023-04-09|
|1196|2023-04-10|
|1197|2023-04-11|
|1198|2023-04-12|
|1199|2023-04-13|
|1200|2023-04-14|
|1201|2023-04-15|
|1202|2023-04-16|
|1203|2023-04-17|
|1204|2023-04-18|
|1205|2023-04-19|
|1206|2023-04-20|
|1207|2023-04-21|
|1208|2023-04-22|
|1209|2023-04-23|
|1210|2023-04-24|
|1211|2023-04-25|
|1212|2023-04-26|
|1213|2023-04-27|
|1214|2023-04-28|
|1215|2023-04-29|
|1216|2023-04-30|
|1217|2023-05-01|
|1218|2023-05-02|
|1219|2023-05-03|
|1220|2023-05-04|
|1221|2023-05-05|
|1222|2023-05-06|
|1223|2023-05-07|
|1224|2023-05-08|
|1225|2023-05-09|
|1226|2023-05-10|
|1227|2023-05-11|
|1228|2023-05-12|
|1229|2023-05-13|
|1230|2023-05-14|
|1231|2023-05-15|
|1232|2023-05-16|
|1233|2023-05-17|
|1234|2023-05-18|
|1235|2023-05-19|
|1236|2023-05-20|
|1237|2023-05-21|
|1238|2023-05-22|
|1239|2023-05-23|
|1240|2023-05-24|
|1241|2023-05-25|
|1242|2023-05-26|
|1243|2023-05-27|
|1244|2023-05-28|
|1245|2023-05-29|
|1246|2023-05-30|
|1247|2023-05-31|
|1248|2023-06-01|
|1249|2023-06-02|
|1250|2023-06-03|
|1251|2023-06-04|
|1252|2023-06-05|
|1253|2023-06-06|
|1254|2023-06-07|
|1255|2023-06-08|
|1256|2023-06-09|
|1257|2023-06-10|
|1258|2023-06-11|
|1259|2023-06-12|
|1260|2023-06-13|
|1261|2023-06-14|
|1262|2023-06-15|
|1263|2023-06-16|
|1264|2023-06-17|
|1265|2023-06-18|
|1266|2023-06-19|
|1267|2023-06-20|
|1268|2023-06-21|
|1269|2023-06-22|
|1270|2023-06-23|
|1271|2023-06-24|
|1272|2023-06-25|
|1273|2023-06-26|
|1274|2023-06-27|
|1275|2023-06-28|
|1276|2023-06-29|
|1277|2023-06-30|
|1278|2023-07-01|
|1279|2023-07-02|
|1280|2023-07-03|
|1281|2023-07-04|
|1282|2023-07-05|
|1283|2023-07-06|
|1284|2023-07-07|
|1285|2023-07-08|
|1286|2023-07-09|
|1287|2023-07-10|
|1288|2023-07-11|
|1289|2023-07-12|
|1290|2023-07-13|
|1291|2023-07-14|
|1292|2023-07-15|
|1293|2023-07-16|
|1294|2023-07-17|
|1295|2023-07-18|
|1296|2023-07-19|
|1297|2023-07-20|
|1298|2023-07-21|
|1299|2023-07-22|
|1300|2023-07-23|
|1301|2023-07-24|
|1302|2023-07-25|
|1303|2023-07-26|
|1304|2023-07-27|
|1305|2023-07-28|
|1306|2023-07-29|
|1307|2023-07-30|
|1308|2023-07-31|
|1309|2023-08-01|
|1310|2023-08-02|
|1311|2023-08-03|
|1312|2023-08-04|
|1313|2023-08-05|
|1314|2023-08-06|
|1315|2023-08-07|
|1316|2023-08-08|
|1317|2023-08-09|
|1318|2023-08-10|
|1319|2023-08-11|
|1320|2023-08-12|
|1321|2023-08-13|
|1322|2023-08-14|
|1323|2023-08-15|
|1324|2023-08-16|
|1325|2023-08-17|
|1326|2023-08-18|
|1327|2023-08-19|
|1328|2023-08-20|
|1329|2023-08-21|
|1330|2023-08-22|
|1331|2023-08-23|
|1332|2023-08-24|
|1333|2023-08-25|
|1334|2023-08-26|
|1335|2023-08-27|
|1336|2023-08-28|
|1337|2023-08-29|
|1338|2023-08-30|
|1339|2023-08-31|
|1340|2023-09-01|
|1341|2023-09-02|
|1342|2023-09-03|
|1343|2023-09-04|
|1344|2023-09-05|
|1345|2023-09-06|
|1346|2023-09-07|
|1347|2023-09-08|
|1348|2023-09-09|
|1349|2023-09-10|
|1350|2023-09-11|
|1351|2023-09-12|
|1352|2023-09-13|
|1353|2023-09-14|
|1354|2023-09-15|
|1355|2023-09-16|
|1356|2023-09-17|
|1357|2023-09-18|
|1358|2023-09-19|
|1359|2023-09-20|
|1360|2023-09-21|
|1361|2023-09-22|
|1362|2023-09-23|
|1363|2023-09-24|
|1364|2023-09-25|
|1365|2023-09-26|
|1366|2023-09-27|
|1367|2023-09-28|
|1368|2023-09-29|
|1369|2023-09-30|
|1370|2023-10-01|
|1371|2023-10-02|
|1372|2023-10-03|
|1373|2023-10-04|
|1374|2023-10-05|
|1375|2023-10-06|
|1376|2023-10-07|
|1377|2023-10-08|
|1378|2023-10-09|
|1379|2023-10-10|
|1380|2023-10-11|
|1381|2023-10-12|
|1382|2023-10-13|
|1383|2023-10-14|
|1384|2023-10-15|
|1385|2023-10-16|
|1386|2023-10-17|
|1387|2023-10-18|
|1388|2023-10-19|
|1389|2023-10-20|
|1390|2023-10-21|
|1391|2023-10-22|
|1392|2023-10-23|
|1393|2023-10-24|
|1394|2023-10-25|
|1395|2023-10-26|
|1396|2023-10-27|
|1397|2023-10-28|
|1398|2023-10-29|
|1399|2023-10-30|
|1400|2023-10-31|
|1401|2023-11-01|
|1402|2023-11-02|
|1403|2023-11-03|
|1404|2023-11-04|
|1405|2023-11-05|
|1406|2023-11-06|
|1407|2023-11-07|
|1408|2023-11-08|
|1409|2023-11-09|
|1410|2023-11-10|
|1411|2023-11-11|
|1412|2023-11-12|
|1413|2023-11-13|
|1414|2023-11-14|
|1415|2023-11-15|
|1416|2023-11-16|
|1417|2023-11-17|
|1418|2023-11-18|
|1419|2023-11-19|
|1420|2023-11-20|
|1421|2023-11-21|
|1422|2023-11-22|
|1423|2023-11-23|
|1424|2023-11-24|
|1425|2023-11-25|
|1426|2023-11-26|
|1427|2023-11-27|
|1428|2023-11-28|
|1429|2023-11-29|
|1430|2023-11-30|
|1431|2023-12-01|
|1432|2023-12-02|
|1433|2023-12-03|
|1434|2023-12-04|
|1435|2023-12-05|
|1436|2023-12-06|
|1437|2023-12-07|
|1438|2023-12-08|
|1439|2023-12-09|
|1440|2023-12-10|
|1441|2023-12-11|
|1442|2023-12-12|
|1443|2023-12-13|
|1444|2023-12-14|
|1445|2023-12-15|
|1446|2023-12-16|
|1447|2023-12-17|
|1448|2023-12-18|
|1449|2023-12-19|
|1450|2023-12-20|
|1451|2023-12-21|
|1452|2023-12-22|
|1453|2023-12-23|
|1454|2023-12-24|
|1455|2023-12-25|
|1456|2023-12-26|
|1457|2023-12-27|
|1458|2023-12-28|
|1459|2023-12-29|
|1460|2023-12-30|
|1461|2023-12-31|

## 0902 在本機 MySQL Server 的 `tw_election_2020` 資料庫，建立一個檢視表 `presidential_votes_percentage` 顯示每組總統候選人的得票比例。

```sql
SELECT *
  FROM tw_election_2020.presidential_votes_percentage;
```

|num|name|votes|total_votes|votes_percentage|
|---|----|-----|-----------|----------------|
|1|宋楚瑜/余湘|608590|14300940|0.0426|
|2|韓國瑜/張善政|5522119|14300940|0.3861|
|3|蔡英文/賴清德|8170231|14300940|0.5713|

## 0903 在本機 MySQL Server 的 `tw_election_2020` 資料庫，建立一個檢視表 `legislative_at_large_votes_percentage` 顯示每個政黨的不分區立委得票比例。

```sql
SELECT *
  FROM tw_election_2020.legislative_at_large_votes_percentage;
```

|name|votes|total_votes|votes_percentage|
|----|-----|-----------|----------------|
|民主進步黨|4811241|14160138|0.3398|
|中國國民黨|4723504|14160138|0.3336|
|台灣民眾黨|1588806|14160138|0.1122|
|時代力量|1098100|14160138|0.0775|
|親民黨|518921|14160138|0.0366|
|台灣基進|447286|14160138|0.0316|
|綠黨|341465|14160138|0.0241|
|新黨|147373|14160138|0.0104|
|一邊一國行動黨|143617|14160138|0.0101|
|安定力量|94563|14160138|0.0067|
|台灣團結聯盟|50435|14160138|0.0036|
|國會政黨聯盟|40331|14160138|0.0028|
|中華統一促進黨|32966|14160138|0.0023|
|宗教聯盟|31117|14160138|0.0022|
|喜樂島聯盟|29324|14160138|0.0021|
|勞動黨|19941|14160138|0.0014|
|合一行動聯盟|17515|14160138|0.0012|
|台灣維新|11952|14160138|0.0008|
|台澎黨|11681|14160138|0.0008|

## 0904 在本機 MySQL Server 的 `covid19` 資料庫，建立一個檢視表 `most_populated_province` 顯示 `locations` 資料表每個國家人口數最多的州別（或省份），沒有切分州別（或省份）資料的國家不需要包含在該檢視表中。

```sql
SELECT *
  FROM covid19.most_populated_province;
```

|country_name|most_populated_province_name|
|------------|---------------------|
|Australia|New South Wales|
|Belgium|Antwerp|
|Brazil|Sao Paulo|
|Canada|Ontario|
|Chile|Metropolitana|
|China|Guangdong|
|Colombia|Capital District|
|Denmark|Greenland|
|France|Reunion|
|Germany|Nordrhein-Westfalen|
|India|Uttar Pradesh|
|Italy|Lombardia|
|Japan|Tokyo|
|Malaysia|Selangor|
|Mexico|Mexico|
|Moldova|Chisinau|
|Netherlands|Zuid-Holland|
|New Zealand|Cook Islands|
|Nigeria|Kano|
|Pakistan|Punjab|
|Peru|Lima|
|Poland|Mazowieckie|
|Romania|Bucuresti|
|Russia|Moscow|
|Slovakia|Presov|
|Spain|Andalusia|
|Sweden|Stockholm|
|Ukraine|Donetsk Oblast|
|United Kingdom|England|
|US|California|

## 0905 在本機 MySQL Server 的 `covid19` 資料庫，建立一個檢視表 `daily_cases` 顯示每個 `location_id`、`calendar_id` 的每日新增個案數。

```sql
SELECT *
  FROM covid19.daily_cases;
```

|location_id|calendar_id|confirmed|deaths|
|-----------|-----------|---------|------|
|1|22|NULL|NULL|
|1|23|0|0|
|1|24|0|0|
|1|25|0|0|
|1|26|0|0|
...|...|...|...|
|955|1160|0|0|
|955|1161|0|0|
|955|1162|0|0|
|955|1163|149|3|
|955|1164|0|0|

`(328041, 4)`